### ISSUE TITLE
NSTextView scrolling broken

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-gui#83]
I am getting the following exception when scrolling past the end of a text view by adding more text...  Please see NSTextView_test in my repositories.  Run it and simply keep typing until you get past the end of the document.   You will see this: 

2020-09-11 13:52:39.277 NSTextView_test[28302:28302] run_for_character_index failed for 144
Throwing 0x47f9768, in flight exception: 0x48ec898
Exception caught by C++: 0
2020-09-11 13:52:39.285 NSTextView_test[28302:28302] run_for_character_index failed for 145
Throwing 0x47f9768, in flight exception: 0x47f9768
Exception caught by C++: 0
2020-09-11 13:52:39.303 NSTextView_test[28302:28302] run_for_character_index failed for 146
Throwing 0x47f9768, in flight exception: 0x47f9768
Exception caught by C++: 0

**Comment by fredkiefer** [comment]
I committed a change that should fix the exception. What still remains is that the text view in the example is not scrollable and characters at the end won't be displayed anywhere. This results in a warning from GSLayoutManager.

**Comment by gcasa** [comment]
It's scrollable on macOS.  I don't understand why it wouldn't be on GNUstep.

**Comment by gcasa** [comment]
![Untitled0](https://user-images.githubusercontent.com/27943/92979808-e0dff480-f461-11ea-801a-29fd664aad6e.png)
![Untitled](https://user-images.githubusercontent.com/27943/92979813-e3424e80-f461-11ea-9920-b3429de22400.png)

**Comment by gcasa** [comment]
Still getting the warning.  This view IS scrollable.  I'm wondering why you're saying it's not.

**Comment by fredkiefer** [comment]
It isn't scrollable for me on GNUstep. Where did you take the screenshot?
I am currently working on getting this view scrollable when decoding on GNUstep. If this already working for you, I rather should stop.

As for the warning you are mentioning. The original error you reported was an exception, after my change you only should get a warning with a completely different text that is caused by the view not being scrollable on GNUstep. 
You have got me completely confused here

**Comment by fredkiefer** [comment]
Now this text view is scrollable on GNUstep too.

**Comment by gcasa** [comment]
macOS
